name: Dependabot

on: pull_request_target

permissions:
  pull-requests: write

jobs:
  dependabot:
    name: Approve and enable auto-merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.APPROVE_AND_AUTO_MERGE_TOKEN }}

    steps:
      - name: Approve the pull request
        run: gh pr review --approve "$PR_URL"

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
